[package]
name = "crypto_kit"
version = "0.1.0"
authors = ["ccdle12 <chris.coverdale24@gmail.com>"]
edition = "2018"

[dependencies]
num-bigint = { version = "0.2", features = ["rand"] }
rand = "0.5"
num-traits = "0.2.8"
sha2 = "0.8.0"
